[package]
name = "masakk1/afui"
version = "0.3.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.2.0"
# Signal = "sleitnick/signal@1.4.0"